apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: {{ .Values.environment.namespace | quote }}
  labels:
    app.kubernetes.io/name: finopsiq
    app.kubernetes.io/component: api-gateway
  annotations:
    azure.workload.identity/client-id: {{ .Values.services.apiGateway.serviceAccountClientId | quote }}
