environment:
  name: dev
  namespace: finopsiq-dev
workloadIdentity:
  tenantId: "22dc2419-3ab3-4f27-905a-945315d19d95"
config:
  secretName: finopsiq-dev-app-config
  keyVaultName: kv-finopsiq-dev
  env:
    AZURE_TENANT_ID: "22dc2419-3ab3-4f27-905a-945315d19d95"
    STORAGE_PROVIDER: cosmos
    STORAGE_DATA_DIR: /tmp/finopsiq/storage
    DATA_RAW_DIR: /tmp/finopsiq/raw
    DATA_PROCESSED_DIR: /tmp/finopsiq/processed
    DATA_EMBEDDINGS_DIR: /tmp/finopsiq/embeddings
    COSMOS_ENDPOINT: "https://cosmos-finopsiq-dev.documents.azure.com:443/"
    COSMOS_DATABASE: finopsiq
    SERVICE_BUS_NAMESPACE: "sb-finopsiq-dev.servicebus.windows.net"
    SERVICE_BUS_TOPIC: finops-events
    EVENT_PROVIDER: service_bus
    AZURE_STORAGE_ACCOUNT_URL: "https://stfinopsiqdev.blob.core.windows.net/"
    AZURE_STORAGE_CONTAINER: finops-raw
    USE_MANAGED_IDENTITY: "true"
    AUTH_MODE: entra
    APPLICATIONINSIGHTS_CONNECTION_STRING: ""
    KEY_VAULT_URL: "https://kv-finopsiq-dev.vault.azure.net/"
    INTERNAL_API_AUDIENCE: api://azure-cost-advisor-services
    AZURE_OPENAI_ENDPOINT: "https://oai-finopsiq-dev.openai.azure.com/"
    AZURE_OPENAI_DEPLOYMENT_NAME: gpt-4.1-mini
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT: text-embedding-3-small
    AZURE_SEARCH_ENDPOINT: "https://search-finopsiq-dev.search.windows.net"
    AZURE_SEARCH_INDEX_NAME: finops-knowledge
    AZURE_SEARCH_SEMANTIC_CONFIG: finops-semantic
ingress:
  enabled: true
  className: azure-application-gateway
  hostname: ""
  sslCertificateName: ""
  sslRedirect: false
services:
  frontend:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/frontend
      tag: f45015
    serviceAccountClientId: "abf849a7-443b-4013-9105-1e1ba521a788"
    env:
      NEXT_PUBLIC_API_URL: ""
  apiGateway:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/api-gateway
      tag: f45015
    serviceAccountClientId: "24c7fc4d-86c8-422d-bdb1-b371eb570acd"
  auth:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/auth-service
      tag: f45015
    serviceAccountClientId: "fc23dd8f-7559-468f-8d25-20a232183691"
  collection:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/collection-service
      tag: f45015
    serviceAccountClientId: "1451cd50-e3e0-4f1b-9131-f0052abbf995"
  processing:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/processing-service
      tag: f45015
    serviceAccountClientId: "4d514f4a-65d7-4959-a466-e07964b34ea0"
  ai:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/ai-service
      tag: f45015
    serviceAccountClientId: "fadb169c-3f39-4928-bbd2-cccd8f376300"
  notification:
    image:
      repository: acrfinopsiqdev.azurecr.io/finopsiq/notification-service
      tag: f45015
    serviceAccountClientId: "cbf9297d-d188-4831-8cc0-952259687fd9"
