environment:
  name: prod
  namespace: finopsiq-prod

config:
  secretName: finopsiq-prod-app-config

ingress:
  enabled: true
  className: azure-application-gateway
  hostname: ""
  sslCertificateName: ""
  sslRedirect: true

services:
  frontend:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/frontend
      tag: prod
    env:
      NEXT_PUBLIC_API_URL: ""
  apiGateway:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/api-gateway
      tag: prod
  auth:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/auth-service
      tag: prod
  collection:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/collection-service
      tag: prod
  processing:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/processing-service
      tag: prod
  ai:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/ai-service
      tag: prod
  notification:
    image:
      repository: acrfinopsiqprod.azurecr.io/finopsiq/notification-service
      tag: prod
