apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ .Values.environment.namespace | quote }}
  labels:
    app.kubernetes.io/name: finopsiq
    app.kubernetes.io/component: frontend
  annotations:
    azure.workload.identity/client-id: {{ .Values.services.frontend.serviceAccountClientId | quote }}
