apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finopsiq-prod
  namespace: argocd
spec:
  project: finopsiq
  source:
    repoURL: https://github.com/AzureFinOpsIQ/FinOpsIQ-Helm.git
    targetRevision: main
    path: charts/finopsiq
    helm:
      valueFiles:
        - prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finopsiq-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
